# Generated by Django 5.2.12 on 2026-03-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_token_alter_appointment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time')},
        ),
    ]
