# Generated by Django 5.2.12 on 2026-03-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'token']},
        ),
    ]
